author: Raniy, 10102
database: false
description: "Provides an easy to use method for players to emote, and staff/moderators to add and remove emotes."
main: info.omgwtfhax.bukkitplugins.owhemotes.OWHEmotes2_0
name: OWHEmotes2_0
startup: postworld
url: https://github.com/Raniy/OWHEmotes2
version: 0.0.2
depend: [Vault]
commands:
    addemote:
        description: "Adds an Emote."
        usage: "/addemote <name> <style(third=0,p2p=1)> <message>"
        aliases: [ae,emote add]
    deleteemote:
        description: "Removes an Emote."
        usage: "/deleteemote <command/name> <style(third=0,p2p=1)"  
        aliases: [de,emote delete]
    listemotes:
        description: "Removes an Emote."
        usage: "/listemotes [character]" 
        aliases: [le,emote list]
    reloademotes:
        description: "Reload the Emotes plugin."
        usage: "/reloademotes | You see this message. possibly 
other things might happen..."
    emoteall:
        description: "Cause all players to use an Emote."
        usage: "/emoteall [Emote]"
    reloademotes:
        description: "Reload the OWHEmotes plugin"
        usage: "/reloademotes"